import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import favicon from "@/favicon.ico";
import "./globals.css";

export const metadata: Metadata = {
  title: "Atlantic Labs",
  description: "Generated by create next app",
  icons: favicon.src,
};

const raleway = Raleway({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
